/**
 * VerificationStrategy — enum for verification types.
 * Equivalent to Java VerificationStrategy enum — ALL values included.
 */
export enum VerificationStrategy {
  PAGE_TITLE = "PAGE_TITLE",
  LOCATOR_VISIBLE = "LOCATOR_VISIBLE",
  LOCATOR_NOT_VISIBLE = "LOCATOR_NOT_VISIBLE",
  CONTAINS_TEXT = "CONTAINS_TEXT",
  DOES_NOT_CONTAIN_TEXT = "DOES_NOT_CONTAIN_TEXT",
  CONTAINS_TEXT_ARR = "CONTAINS_TEXT_ARR",
  CONTAINS_TEXT_PATTERN = "CONTAINS_TEXT_PATTERN",
  CONTAINS_TEXT_PATTERN_ARR = "CONTAINS_TEXT_PATTERN_ARR",
  MATCHES_TEXT = "MATCHES_TEXT",
  ATTRIBUTE = "ATTRIBUTE",
  CLASS = "CLASS",
  COUNT = "COUNT",
  NAME = "NAME",
  CSS = "CSS",
  ID = "ID",
  HAS_VALUE = "HAS_VALUE",
  HAS_VALUES = "HAS_VALUES",
  IS_CHECKED = "IS_CHECKED",
  IS_EDITABLE = "IS_EDITABLE",
  IS_DISABLED = "IS_DISABLED",
  IS_ENABLED = "IS_ENABLED",
  IS_EMPTY = "IS_EMPTY",
  IS_FOCUSED = "IS_FOCUSED",
  HAS_JS_PROPERTY = "HAS_JS_PROPERTY",
  URL = "URL",
  OBJECT = "OBJECT",
  COLLECTION = "COLLECTION",
}
